apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: product-api
    k8s/version: v1
    tier: application
    version: v1
  name: product-api
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: product-api
      k8s/version: v1
      tier: application
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: product-api
        k8s/version: v1
        tier: application
        version: v1
    spec:
      containers:
      - name: product-api
        image: hash/product-api:${VERSION}
        env:
        - name: NODE_ENV
          value: ${NODE_ENV}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 180
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          failureThreshold: 3
          httpGet:
            path: v1/healthcheck
            port: 8080
            scheme: HTTP
            httpHeaders:
              - name: Host
                value: localhost
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 700m
            memory: 700Mi
          requests:
            cpu: 500m
            memory: 500Mi
