apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: user-api
    k8s/version: v1
    tier: application
    version: v1
  name: user-api
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: user-api
      k8s/version: v1
      tier: application
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-api
        k8s/version: v1
        tier: application
        version: v1
    spec:
      containers:
      - name: user-api
        image: hash/user-api:${VERSION}
        env:
        - name: NODE_ENV
          value: ${NODE_ENV}
        ports:
        - containerPort: 50051
          protocol: TCP
        resources:
          limits:
            cpu: 700m
            memory: 700Mi
          requests:
            cpu: 500m
            memory: 500Mi
