name: apps-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  product-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: 14
      - run: cp .env.example .env
      - run: make product/ci

  user-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: cp .env.example .env
      - run: make user/ci